apiVersion: ondemand.dev/v1
kind: Pun
metadata:
  name: "$DNS_OOD_USER"
  namespace: "$NAMESPACE"
  labels:
    ood-cluster: "$OOD_INSTANCE"
spec: 
  user: "$OOD_USER"
  httpd:
    image: "$KOODO_IMAGE"
