FROM rockylinux/rockylinux:9 as base
RUN dnf -y install https://yum.osc.edu/ondemand/4.0/ondemand-release-web-4.0-1.el9.noarch.rpm
RUN dnf -y update && \
    dnf install -y dnf-utils epel-release && \
    dnf module enable -y ruby:3.3 nodejs:20 && \
    dnf install -y ondemand && \
    dnf clean all && rm -rf /var/cache/dnf/*
RUN /usr/libexec/httpd-ssl-gencerts
RUN systemctl enable httpd

FROM base

RUN dnf install -y gettext lua-socket sssd-client
COPY pod_proxy.lua /opt/ood/mod_ood_proxy/lib/pun_proxy.lua
COPY pun.conf.erb /opt/ood/nginx_stage/templates/pun.conf.erb
COPY operator-utils /opt/krood/utils
COPY entrypoint.sh /opt/krood/entrypoint.sh
CMD ["sh", "/opt/krood/entrypoint.sh"]
